export const OpenAI = {
  chatModels: [
    {
      description: "GPT 3.5 Turbo，适用于各种文本生成和理解任务",
      displayName: "GPT-3.5 Turbo",
      enabled: true,
      functionCall: true,
      id: "gpt-3.5-turbo",
      tokens: 16_385,
    },
    {
      displayName: "GPT-3.5 Turbo (0125)",
      functionCall: true,
      id: "gpt-3.5-turbo-0125",
      tokens: 16_385,
    },
    {
      displayName: "GPT-3.5 Turbo (1106)",
      functionCall: true,
      id: "gpt-3.5-turbo-1106",
      tokens: 16_385,
    },
    {
      displayName: "GPT-3.5 Turbo Instruct",
      id: "gpt-3.5-turbo-instruct",
      tokens: 4096,
    },
    {
      displayName: "GPT-3.5 Turbo 16K",
      id: "gpt-3.5-turbo-16k",
      tokens: 16_385,
    },
    {
      displayName: "GPT-3.5 Turbo (0613)",
      id: "gpt-3.5-turbo-0613",
      legacy: true,
      tokens: 4096,
    },
    {
      displayName: "GPT-3.5 Turbo 16K (0613)",
      id: "gpt-3.5-turbo-16k-0613",
      legacy: true,
      tokens: 4096,
    },
    {
      displayName: "GPT-4 Turbo Preview",
      functionCall: true,
      id: "gpt-4-turbo-preview",
      tokens: 128_000,
    },
    {
      displayName: "GPT-4 Turbo Preview (0125)",
      functionCall: true,
      id: "gpt-4-0125-preview",
      tokens: 128_000,
    },
    {
      description: "GPT-4 视觉预览版，支持视觉任务",
      displayName: "GPT-4 Turbo Vision Preview",
      id: "gpt-4-vision-preview",
      tokens: 128_000,
      vision: true,
    },
    {
      displayName: "GPT-4 Turbo Vision Preview (1106)",
      id: "gpt-4-1106-vision-preview",
      tokens: 128_000,
      vision: true,
    },
    {
      displayName: "GPT-4 Turbo Preview (1106)",
      functionCall: true,
      id: "gpt-4-1106-preview",
      tokens: 128_000,
    },
    {
      displayName: "GPT-4",
      functionCall: true,
      id: "gpt-4",
      tokens: 8192,
    },
    {
      displayName: "GPT-4 (0613)",
      functionCall: true,
      id: "gpt-4-0613",
      tokens: 8192,
    },
    {
      displayName: "GPT-4 32K",
      functionCall: true,
      id: "gpt-4-32k",
      tokens: 32_768,
    },
    {
      displayName: "GPT-4 32K (0613)",
      functionCall: true,
      id: "gpt-4-32k-0613",
      tokens: 32_768,
    },
    {
      description: "GPT-4 Turbo 视觉版",
      displayName: "GPT-4 Turbo",
      enabled: true,
      functionCall: true,
      id: "gpt-4-turbo",
      tokens: 128_000,
      vision: true,
    },
    {
      description: "GPT-4 Turbo 视觉版 (240409)",
      displayName: "GPT-4 Turbo Vision (240409)",
      functionCall: true,
      id: "gpt-4-turbo-2024-04-09",
      tokens: 128_000,
      vision: true,
    },
    {
      displayName: "GPT-4 ALL",
      files: true,
      functionCall: true,
      id: "gpt-4-all",
      tokens: 32_768,
      vision: true,
    },
  ],
  enabled: true,
  id: "openai",
};

export const Ollama = {
  chatModels: [
    {
      displayName: "Gemma 7B",
      enabled: true,
      functionCall: false,
      id: "gemma",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Gemma 2B",
      enabled: true,
      functionCall: false,
      id: "gemma:2b",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Llama2 Chat 13B",
      functionCall: false,
      id: "llama2:13b",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Llama2 Chat 7B",
      enabled: true,
      functionCall: false,
      id: "llama2",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Llama2 Chat 70B",
      functionCall: false,
      id: "llama2:70b",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Llama2 CN 13B",
      functionCall: false,
      id: "llama2-chinese:13b",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Llama2 CN 7B",
      functionCall: false,
      id: "llama2-chinese",
      tokens: 4000,
      vision: false,
    },
    {
      displayName: "Code Llama 7B",
      functionCall: false,
      id: "codellama",
      tokens: 16_000,
      vision: false,
    },
    {
      displayName: "Code Llama 34B",
      functionCall: false,
      id: "codellama:34b",
      tokens: 16_000,
      vision: false,
    },
    {
      displayName: "Code Llama 70B",
      functionCall: false,
      id: "codellama:70b",
      tokens: 16_000,
      vision: false,
    },
    {
      displayName: "Code Llama 7B (Python)",
      functionCall: false,
      id: "codellama:python",
      tokens: 16_000,
      vision: false,
    },
    {
      displayName: "Mistral",
      enabled: true,
      functionCall: false,
      id: "mistral",
      tokens: 4800,
      vision: false,
    },
    {
      displayName: "Mixtral 8x7B",
      enabled: true,
      functionCall: false,
      id: "mixtral",
      tokens: 32_000,
      vision: false,
    },
    {
      displayName: "Qwen Chat 4B",
      functionCall: false,
      id: "qwen",
      tokens: 32_768,
      vision: false,
    },
    {
      displayName: "Qwen Chat 7B",
      enabled: true,
      functionCall: false,
      id: "qwen:7b",
      tokens: 32_768,
      vision: false,
    },
    {
      displayName: "Qwen Chat 14B",
      functionCall: false,
      id: "qwen:14b",
      tokens: 32_768,
      vision: false,
    },
    {
      displayName: "Qwen Chat 72B",
      functionCall: false,
      id: "qwen:72b",
      tokens: 32_768,
      vision: false,
    },
    {
      displayName: "LLaVA 7B",
      functionCall: false,
      id: "llava",
      tokens: 4000,
      vision: true,
    },
    {
      displayName: "LLaVA 13B",
      functionCall: false,
      id: "llava:13b",
      tokens: 4000,
      vision: true,
    },
    {
      displayName: "LLaVA 34B",
      functionCall: false,
      id: "llava:34b",
      tokens: 4000,
      vision: true,
    },
    // TODO: 在单独支持千问之后这些 Qwen 模型需要移动到千问的配置中
    {
      displayName: "Qwen Plus",
      functionCall: true,
      id: "qwen-plus",
      tokens: 30_000,
      vision: false,
    },
    {
      displayName: "Qwen Turbo",
      functionCall: true,
      id: "qwen-turbo",
      tokens: 6000,
      vision: false,
    },
    {
      displayName: "Qwen Max",
      functionCall: true,
      id: "qwen-max",
      tokens: 6000,
      vision: false,
    },
    {
      displayName: "Qwen Max Long",
      functionCall: true,
      id: "qwen-max-longcontext",
      tokens: 28_000,
      vision: false,
    },
    {
      displayName: "Qwen VL Max",
      functionCall: false,
      id: "qwen-vl-max",
      tokens: 6000,
      vision: true,
    },
    {
      displayName: "Qwen VL Plus",
      functionCall: false,
      id: "qwen-vl-plus",
      tokens: 30_000,
      vision: true,
    },
  ],
  id: "ollama",
};
