export const s = [
    "To explore the morphological variation of prey capture behaviour, here we extend the examination to a higher fineness ratio 0.5. Accordingly, first, the flow field (see supplementary movie 5) for the paddling medusa (of fixed material properties *c<sub>st</sub>* *=*18.5 and *cbe* *=*0.03) is simulated, and then the detailed entrainment pattern/dynamics (see supplementary movie 6) of floating infinitesimal prey particles is obtained. Figure 22 shows contours of forward-time (figure 22*a*1) and backward-time (figure 22*a*1) FTLE fields and pLCS that are computed (using (3.7)–(3.10] for five propulsive cycles (*t=*5*T*), so as to deliver a clear picture for predator–prey encounter. Note that, for a higher fineness ratio 0.5 of the bell, the sizes of the forward-time FTLE loops (figure 22*a*1), i.e. target zones, shrink significantly (compared to figure 9*a*; *h*<sub>0</sub>/*d*0 *=*0.3). This implies that an oblate-type medusa (of low fineness ratio) is a better feeding-current-generating hunter compared to a prolate one. Second, instead of focusing on a cluster of prey particles, in this case the entrainment (see supplementary movie 7) of individual prey that originate inside or outside (figure 22*a*1) FTLE loops is revealed, which provides clearer information on their placement within the capture boundary (i.e. pLCS in figure 22*a*2) or near wake. The appended positions (at *t=*5*T*) of pink- and blue-coloured prey particles in figure 22(*a*2), which were initially stationed as in figure 22(*a*1), clearly shows that the pink prey that originated inside the forward-time FTLE loops are entrained within the pLCS/capture boundary demarcated by the dark colour high ridges of the backward-time FTLE field (figure 22*a*2), whereas the blue-coloured particles escape to the adjacent outer area (see also supplementary movie 7).",
    "Cycle",
    "Inf.,*h* Figure 22. For caption see next page.",
    "0",
    "/ Figure 22. (cntd). The effect of inertia on prey encounter and capture by a prolate-type jellyfish (*h*<sub>0</sub>/*d*0 *=*0.5). (*a*1,*a*2) For infinitesimal prey, plotted are contours of FTLE fields (pLCS) and displaced prey position due to the paddling jellyfish motion. Here *Re=*100 and *F<sub>b</sub>* *=*5.4. (*a*1) The forward-time FTLE field, where green-coloured high ridges reveal Lagrangian coherent structures (pLCS) computed at *t=*5*T*. The pinkand blue-coloured prey are initially located inside and outside the upstream pLCS lobes, and their swept positions are tracked as the jellyfish paddles forwards. (*a*2) The corresponding backward-time FTLE field plus appended position of swept prey at *t=*5*T*; pLCS boundaries are denoted in dark black colour. (*b*1,*b*2) For suspended inertial prey with no escape force (*R=*2/3, *a<sub>E</sub>* *=*0), plotted are contours of FTLE fields (pLCS) and displacement of prey positions due to the paddling jellyfish motion. Here *Re=*100 and *F<sub>b</sub>* *=*5.4. d 0",
    "# =",
    "0.3 NESCF,*h* Figure 23. The effect of prey inertia on the variation of forward-time FTLE loops/fingers for a prolate-like (*h*<sub>0</sub>/*d*0 *=*0.5) jellyfish/predator. Here *Re=*100 and *Fb* *=*5.4.",
    "0",
    "/ Figure 24. An image of a real *A. aurita* (moon jellyfish) that has relatively small tentacles that are used for",
    "# d",
    "0",
    "# =",
    "0.3 OESCF,*h* prey capture/filtering. Source: https\\://commons.wikimedia.org/wiki/File:Jellyfish\\_(22155766231).jpg. *Supplementary movies.* Supplementary movies are available at https\\://doi.org/10.1017/jfm.2020.1069.",
    "0",
    "/ *Funding.* The work is supported by NRF grant no. 2017R1D1A1A09000952, South Korea.",
    "# d",
    "0",
    "# =",
    "0.3 OESCF-Th,*h* *Declaration of interests.* The authors report no conflict of interest. Amalendu Sau https\\://orcid.org/0000-0001-8263-0740.",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.3 NRESCF,*h*",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.3 NRESCF-Th,*h*",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.3 Inf.,*h*",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.5 NESCF,*h*",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.5 1st",
    "0.553",
    "(64 % of 5th) 0.527(63 % of 5th) 0.480(50 % of 5th) 0.593(72 % of 5th) 0.520(81 % of 5th) 0.477(56 % of 5th) 0.260(61 % of 5th) 0.226(55 % of 5th) 2nd",
    "0.618(72 % of 5th) 0.591(71 % of 5th) 0.656(60 % of 5th) 0.746(91 % of 5th) 0.558(87 % of 5th) 0.663(77 % of 5th) 0.312(73 % of 5th) 0.285(69 % of 5th) 4th",
    "0.822(95 % of 5th) 0.791(95 % of 5th) 0.969(88 % of 5th) 0.767(94 % of 5th) 0.623(97 % of 5th) 0.817(95 % of 5th) 0.392(92 % of 5th) 0.377(92 % of 5th) 5th",
    "0.862",
    "0.829",
    "(96 % of Inf.) 1.094(132 % ofNESCF) 0.820(99 % ofNESCF) 0.639(77 % ofNESCF) 0.857(103 % ofNESCF) 0.425(49 % of Inf.,*h*",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.3) 0.411(97 % of Inf.,*h*",
    "0",
    "/",
    "# d",
    "0",
    "# =",
    "0.5)",
    "Table 3. Prey-specific cycle-to-cycle variation of the average clearance rate",
    "# CR",
    "# /",
    "# CR",
    "ref",
    "over a range of applied paddling force, 2",
    "# ≤",
    "# F",
    "b",
    "# ≤",
    "24; ideal infinitesimal (Inf.), inertial (NESCF; with no escape force), opposite escape force (OESCF), opposite escape force at threshold shear (OESCF-Th), normal escape force (NRESCF), and normal escapeforce at threshold shear (NRESCF-Th). Here",
    "# Re",
    "# =",
    "100 and",
    "# a",
    "E",
    "# =",
    "0",
    "# .",
    "5\\.",
    "(*a*1)",
    "9",
    "3 2 6 5 9 8",
    "9 47 7",
    "3 2",
    "1 1 8",
    "5",
    "6 4 7 96 5 4 2",
    "9 8 8",
    "7",
    "7 6 6 5 5",
    "4",
    "4 3 3",
    "2 21 1",
    "(*a*2)"
];

export const t = [
    "为了探索猎物捕获行为的形态学变化，我们将检查范围扩大到更高的细度比0.5。因此，首先，模拟划水水母（具有固定材料特性*c<sub>st</sub>**=*18.5和*cbe**=*0.03）的流场（见补充电影5），然后获得漂浮的无穷小猎物颗粒的详细夹带模式/动力学（见补充影片6）。图22显示了五个推进周期（*t=*5*t*）（使用（3.7）-（3.10]）计算的正向时间（图22*a*1）和反向时间（图22-a*1）FTLE场和pLCS的轮廓，以便为捕食者-猎物的相遇提供清晰的画面。请注意，对于更高的钟形细度比0.5，正向时间FTLE环路（图22*a*1）的大小，即目标区域，显著收缩（与图9*a*相比；*h*<sub>0</sub>/*d*0*=*0.3）。这意味着扁体型的美杜莎（细度比较低）与长体型的相比，是一种更好的产流猎人。其次，在这种情况下，不关注猎物颗粒的集群，而是揭示了源自FTLE回路内部或外部（图22*a*1）的单个猎物的夹带（见补充电影7），这提供了关于它们在捕获边界（即图22*a*2中的pLCS）或近尾流内的位置的更清晰信息。图22（*a*2）中粉红色和蓝色猎物颗粒的附加位置（*t=*5*t*），最初如图22（*a*1）所示，清楚地表明，起源于前向时间FTLE环内的粉红色猎物被卷入由后向时间FTLE场的深色高脊划定的pLCS/捕获边界内（图22*a*2），而蓝色颗粒则逃逸到相邻的外部区域（另见补充电影7）。",
    "周期",
    "Inf.，*h*图22。标题见下页。",
    "0",
    "/图22。（cntd）。惯性对细长型水母遭遇和捕获猎物的影响（*h*<sub>0</sub>/*d*0*=*0.5）。（*a*1，*a*2）对于无穷小的猎物，绘制了FTLE场（pLCS）的轮廓和由于划水水母运动而移位的猎物位置。这里*Re=*100和*F<sub>b</sub>**=*5.4。（*a*1）正向时间FTLE场，其中绿色的高脊揭示了在*t=*5*t*计算的拉格朗日相干结构（pLCS）。粉红色和蓝色的猎物最初位于上游pLCS叶的内侧和外侧，当水母向前划动时，会跟踪它们的掠过位置。（*a*2）对应的向后时间FTLE场加上*t=*5*t*处被扫猎物的附加位置；pLCS边界用深黑色表示。（*b*1，*b*2）对于没有逃脱力的悬挂惯性猎物（*R=*2/3，*a<sub>E</sub>**=*0），绘制了FTLE场（pLCS）的轮廓和由于划水水母运动引起的猎物位置的位移。",
    "这里*Re=*100和*F<sub>b</sub>**=*5.4。d 0",
    "# =",
    "0.3 NESCF，*h*图23。捕食惯性对细长类（*h*<sub>0</sub>/*d*0*=*0.5）水母/捕食者前向时间FTLE环/指变化的影响。",
    "这里*Re=*100和*Fb**=*5.4。",
    "0",
    "/图24。真实*a的图像。",
    "aurita*（月水母），有相对较小的触手，用于",
    "d",
    "0",
    "# =",
    "0.3 OESCF，*h*猎物捕获/过滤。来源：https://commons.wikimedia.org/wiki/File:Jellyfish\\_（22155766231）.jpg*补充电影。*补充电影可在https://doi.org/10.1017/jfm.2020上获得",
    "2020",
    ".1069.",
    "0",
    "/*资金。*这项工作得到了NRF编号为2017R1D1A1A09000952的资助，韩国。",
    "d",
    "0",
    "# =",
    "0.3 OESCF Th，*h**利益声明。*作者报告没有利益冲突。",
    "Amalendu Sau https://orcid.org/0000-0001-8263-0740。",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.3 NRESCF，*h*",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.3 NRESCF Th，*h*",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.3英寸，*小时*",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.5 NESCF，*h*",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.5 1st",
    "0.553",
    "（第五名的64%）0.527",
    "0.618（第五名的72%）0.591",
    "0.822（第五名的95%）0.791",
    "0.862",
    "0.829",
    "（Inf.的96%）",
    ")",
    "1.094（132%ESCF）0.820（99%的ESCF）0.639（77%的ESCF*",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.3）0.411（Inf.的97%，*h*",
    "0",
    "/",
    "d",
    "0",
    "# =",
    "0.5)",
    "表3。平均清除率的猎物特定周期间变化",
    "#CR",
    "# /",
    "#CR",
    "裁判",
    "在施加的划桨力范围内，2",
    "# ≤",
    "F",
    "b",
    "# ≤",
    "24; 理想无穷小（Inf.）、惯性（NESCF；无逃逸力）、反向逃逸力（OESCF）、阈值剪切下的反向逃逸力。",
    "在这里",
    "关于",
    "# =",
    "100和",
    "一",
    "E",
    "# =",
    "0",
    "# .",
    "5.",
    "（*a*1）",
    "9",
    "3 2 6 5 9 8",
    "9 47 7",
    "3 2",
    "1 1 8",
    "5.",
    "6 4 7 96 5 4 2",
    "9 8 8",
    "7.",
    "7 6 6 5 5",
    "4.",
    "4 3 3",
    "2 21 1",
    "（*a*2）"
];